container_type: SingularityFile
image: https://storage.googleapis.com/medperf-storage/mock-model-cpu-0.0.1.simg
tasks:
  infer:
    input_volumes:
      data_path:
        mount_path: /medperf_data
        type: directory
      parameters_file:
        mount_path: /medperf_parameters.yaml
        type: file
      additional_files:
        mount_path: /medperf_additional_files
        type: directory
    output_volumes:
      output_path:
        mount_path: /medperf_predictions
        type: directory
